version: 2.1

jobs:
  hello-job:
    docker:
      - image: johnbcoughlin/warpii:ci-ubuntu # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: apt-get install -y doxygen ccache
      - restore_cache:
          key: ccache
      - run:
          name: "Ensure ccache directory present"
          command: mkdir -p /root/.ccache
      - run: 
          name: "Build and run tests"
          command: make test CMAKE_BUILD_PARALLEL_LEVEL=2
          environment:
            WARPII_CMAKE_PRESET: ci-ubuntu
            CMAKE_CXX_COMPILER_LAUNCHER: ccache
      - save_cache:
          key: ccache
          paths:
            - /root/.ccache


workflows:
  my-workflow:
    jobs:
      - hello-job
