version: 2.1

jobs:
  hello-job:
    docker:
      - image: johnbcoughlin/warpii:ci-ubuntu # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: 
          name: "Install doxygen"
          command: apt-get install -y doxygen
      - run: 
          name: "Build and run tests"
          command: make test
          environment:
            WARPII_CMAKE_PRESET: ci-ubuntu


workflows:
  my-workflow:
    jobs:
      - hello-job
