name: Deploy doxygen output to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "jack-fix-gh-pages"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    container: johnbcoughlin/warpii:ci-ubuntu
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      WARPIISOFT: /root
      WARPII_CMAKE_PRESET: ci-ubuntu
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          append-timestamp: false  # no need to save a separate cache entry every build, just use the most recent relevant one
          key: ${{ github.job }}-${{ env.WARPII_CMAKE_PRESET }}-linux
          verbose: 2 # Check if cache is working in post action

      - name: Install dependencies
        run: apt-get install -y doxygen

      - name: Build docs
        run: make doc CMAKE_BUILD_PARALLEL_LEVEL=2

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'builds/ci-ubuntu/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
